[build]
  base = "site-next"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

 [[redirects]]
   from = "/illysocial/*"
   to = "https://illysocialv2-app.netlify.app/:splat"
   status = 200
   force = true

 [[redirects]]
   from = "/two"
   to = "https://livepay-app.netlify.app/two"
   status = 200
   force = true

 [[redirects]]
   from = "/settings"
   to = "https://livepay-app.netlify.app/settings"
   status = 200
   force = true

 [[redirects]]
   from = "/modal"
   to = "https://livepay-app.netlify.app/modal"
   status = 200
   force = true

 [[redirects]]
   from = "/cashout"
   to = "https://livepay-app.netlify.app/cashout"
   status = 200
   force = true

 [[redirects]]
   from = "/onboarding"
   to = "https://livepay-app.netlify.app/onboarding"
   status = 200
   force = true

 [[redirects]]
   from = "/livepay/*"
   to = "https://livepay-app.netlify.app/:splat"
   status = 200
   force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
